### ISSUE TITLE
broken link in github deployment page

### ISSUE THREAD

**Issue by abenhamdine** [CleverCloud/doc.clever-cloud.com#104]
in https://www.clever-cloud.com/doc/clever-cloud-overview/add-application/#automatic-deployment-with-github

the link [Adding SSH keys] (https://www.clever-cloud.com/admin-console/ssh-keys/) is broken

**Comment by BlackYoup** [comment]
Hi !

Thanks for the report. Feel free to open a PR if you want to fix it.
The file is here: https://github.com/CleverCloud/doc.clever-cloud.com/blob/master/commons/clever-cloud-overview/add-application.md

The link misses the /doc at its beginning :-)

**Comment by abenhamdine** [comment]
done, PR https://github.com/CleverCloud/doc.clever-cloud.com/pull/105
thx for the instructions.
