### ISSUE TITLE
pico and nano instances are not displayed on the pricing page

### ISSUE THREAD

**Issue by Geal** [CleverCloud/doc.clever-cloud.com#141]
https://www.clever-cloud.com/doc/clever-cloud-overview/pricing/

**Comment by divarvel** [comment]
Maybe this page should just have a link to the pricer

**Comment by divarvel** [comment]
@cnivolle don't you think it would make sense to remove this page or at least make it point to the pricer?
https://www.clever-cloud.com/doc/clever-cloud-overview/pricing/
