### ISSUE TITLE
confusing Rust docs

### ISSUE THREAD

**Issue by Geal** [CleverCloud/doc.clever-cloud.com#142]
on https://www.clever-cloud.com/doc/rust/rust/:
- why is there the mention "be sure that you have listed all your dependencies in Cargo.toml"? Which failure case could happen there, since Rust apps rely on cargo to build?
- shouldn't the Cargo.lock file be mentioned? Since for executables, it should be commited to the repository

**Comment by divarvel** [comment]
Sounds sensible, feel free to submit a PR.

**Comment by divarvel** [comment]
https://github.com/CleverCloud/doc.clever-cloud.com/pull/151
