### ISSUE TITLE
Refresh nodejs documentation

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/doc.clever-cloud.com#147]
Especially the part about pre-installed packages

**Comment by abenhamdine** [comment]
IMHO would be great to document  usage of CACHE_DEPENDENCIES env variable (what it does exactly ?)

**Comment by BlackYoup** [comment]
@divarvel should we document the `CACHE_DEPENDENCIES` per application or in a common page ? I see that haskell, rust and python already have a `CACHE_DEPENDENCIES` section with almost the same explanation

**Comment by BlackYoup** [comment]
See #190
