### ISSUE TITLE
How to Install CFEngine on Ubuntu 16.04

### ISSUE THREAD

**Issue by hitjethva** [CleverCloud/doc.clever-cloud.com#158]
Introduction

CFEngine is a free and open source configuration management system that provides a framework for automatically managing an IT infrastructure.

**Comment by hitjethva** [comment]
Can I write an article on the CFEngine.

**Comment by BlackYoup** [comment]
Hi @hitjethva 

Sorry but we don't use Ubuntu nor CFEngine, so this kind of article won't fit into our documentation. Writing it on your own blog might make more sense :-)
