### ISSUE TITLE
Improve sbt documentation

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/doc.clever-cloud.com#176]
For instance the use of `SBT_DEPLOY_GOAL`, and a how-to for multi-module applications.

**Comment by SadatAnwar** [comment]
To add to this one. 
I am using play2.5 with scala and had some issues with the deployment. For some reason I kept getting errors with the play-sbt dependency not being found finally this worked 

```sbt
resolvers += Resolver.typesafeIvyRepo("releases")
logLevel := Level.Warn


addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.12")
```
Also it was quite hard to find this working setting.

**Comment by divarvel** [comment]
It looks like the issues were caused by the bintray outage
