### ISSUE TITLE
Document CACHE_DEPENDENCIES feature

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/doc.clever-cloud.com#190]
This feature should be documented in a common page for all instances.

Some instances doesn't have it:
- Docker
- Go

Also, haskell, rust and python already have a explanation about this feature, so this has to be removed

**Comment by gaelreyrol** [comment]
This variable is deprecated, we should now use `CC_CACHE_DEPENDENCIES` described in the [environment variables reference](https://www.clever-cloud.com/doc/reference/reference-environment-variables/#variables-you-can-define).
