### ISSUE TITLE
Embed videos in documentation

### ISSUE THREAD

**Issue by waxzce** [CleverCloud/doc.clever-cloud.com#216]
like https://www.youtube.com/watch?v=dxhSjHnrrhA
in https://www.clever-cloud.com/doc/nodejs/nodejs/

**Comment by yoanngrange** [comment]
https://github.com/CleverCloud/doc.clever-cloud.com/pull/228

**Comment by yoanngrange** [comment]
https://github.com/CleverCloud/doc.clever-cloud.com/pull/229

**Comment by divarvel** [comment]
+1 for videos in the documentation, but these videos are more about showcasing than documenting IMO (the source code of the apps is not shown, and it's not explained which dependencies are needed). We can add them as is, but we should open another issue to add a textual explanation (with a link to the github repos, at the very least).
