### ISSUE TITLE
[Meta Issue] How to Deploy X on Clever Cloud

### ISSUE THREAD

**Issue by ldoguin** [CleverCloud/doc.clever-cloud.com#259]
This is a placeholder issue never to be closer. Please have a look at the current list on the wiki: [https://github.com/CleverCloud/doc.clever-cloud.com/wiki/How-to-Deploy-X-on-Clever-Cloud](https://github.com/CleverCloud/doc.clever-cloud.com/wiki/How-to-Deploy-X-on-Clever-Cloud)

To create your own issue please make sure you use the following title:
[Guide] How to deploy a <Framework X> application?

**Comment by RemiBardon** [comment]
Is [the list](https://github.com/CleverCloud/doc.clever-cloud.com/wiki/How-to-Deploy-X-on-Clever-Cloud) ordered ?

I mean, if I want to write a guide concerning a framework, do I have to start with a mainstream one or is it OK to address a "niche" ?

**Comment by ldoguin** [comment]
@RemiBardon Please feel free to contribute with any framework you want. There is no order or preferences.

**Comment by RemiBardon** [comment]
Then [Vapor](vapor.codes) is on my TO-DO list 😀 (It's just Docker, documented in [Vapor docs](docs.vapor.codes), but there are Clever Cloud details to add)

**Comment by gaelreyrol** [comment]
Closing in favor of: https://github.com/orgs/clever-cloud-examples/projects/1
