### ISSUE TITLE
Do not send a Content-Length for gzipped response

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/doc.clever-cloud.com#295]
I'm not sure where this should go or even if it should be here, but some customers sometimes gzip their response and still give a custom content-length, which makes the request "fail".
We should say somewhere that they shouldn't do that

**Comment by judu** [comment]
I'd say, we add a question in the FAQ, with a small paragraph in PHP/Ruby/Python. Because it is most likely to happen on applications that have a nginx/apache front that adds gzip compression afterwards.
