### ISSUE TITLE
Document cellar example with ruby

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/doc.clever-cloud.com#300]
The `endpoint` setting is not really documented, I found out about it by reading the source code.
Here are a few examples (courtesy of a nice user).

## gemfile

```sh
gem 'aws-sdk', '~> 2.3.0'
```

```ruby
Aws.config.update(
  region: 'region', endpoint: "https://#{host}", signature_version: 's3',
  credentials: Aws::Credentials.new('aws_access_key_id', 'aws_secret_access_key')
)

s3 = Aws::S3::Client.new
file_name = 'file.png'
File.open("path/#{file_name}", 'rb') do |file|
  s3.put_object(body: file, bucket: 'bucket', key: file_name)
```

**Comment by 16** [comment]
I just made a [pull request that add cellar doc for Active Storage (RoR)](https://github.com/CleverCloud/doc.clever-cloud.com/pull/390). It uses aws-sdk too, so maybe it can be completed / merged together ?

**Comment by gaelreyrol** [comment]
This issue is now well documented in the [Using Active Storage and Cellar S3](https://www.clever-cloud.com/doc/deploy/application/ruby/by-framework/ruby-on-rails/#using-active-storage-and-cellar-s3) section.
