### ISSUE TITLE
[Angular,Static apps] Document "HTML5 mode"

### ISSUE THREAD

**Issue by judu** [CleverCloud/doc.clever-cloud.com#306]
In Angular, there is a "html5 mode" that needs some configuration to work. Users need to add this to their .htaccess:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^(.*) /index.html [NC,L]
```

We should document it somewhere.

**Comment by gaelreyrol** [comment]
This feature is related to Angular.js which has been replaced by Angular.
