### ISSUE TITLE
[Static] Documentation is poor. We should more explicitely send to the PHP page.

### ISSUE THREAD

**Issue by judu** [CleverCloud/doc.clever-cloud.com#307]
Static documentation is really scarce. We need either a big button to send user to PHP or redirect to a PHP/static page without asking.

Also, on the PHP page, we should make sure that the "apache/static" configuration values are separated from the PHP values. So a user deploying a static app won't drown in the php documentation.

**Comment by gaelreyrol** [comment]
I think this is now well documented, closing.
