### ISSUE TITLE
[S3/Cellar] Specify that the header `Content-Type` is required to get a signed url to put a file ?

### ISSUE THREAD

**Issue by Dnomyar** [CleverCloud/doc.clever-cloud.com#314]
Hi there !

I had to specify `generatePreSignedUrlRequest.withContentType("application/octet-stream")` in order to get it work.

Thanks @divarvel for your help

**Comment by gaelreyrol** [comment]
I am closing this issue because it is not related to the Java example and depends on the action you want to perform with the generation of a pre-signed url.
