### ISSUE TITLE
Deploying jhipster app on Clever Cloud

### ISSUE THREAD

**Issue by savoisn** [CleverCloud/doc.clever-cloud.com#34]
Hi Guys,
Here is a draft of the excerpt of the documentation for deploying Jhipster app on Clever Cloud
# Deploying Jhipster app on Clever Cloud.

Clever Cloud is the new hype in regard of cloud for developers.

Jhipster is the hype in regard of Java web app development.

Of course it has to melt for something great!

Jhipster is very versatile by nature.
And Clever Cloud is not behind.
## Deploying only the executable jar

The straight forward approach
Don't know how to test that. It's described in the documentation but I don't know how to create this kind of application with the administration application.

Pro
Cons
## Deploying on  tomcat

Not much harder than previous approach

tricky especially with environment variable for spring...

Pro
Cons
### build from the source while constructing the images

Jhipster comes with its docker image! So let's use it!
Oh wait... This image while great for developers comes with all the world installed, which gives us an image that is a nearly 2.5 Go in size and takes     roughly 15 min to build. But it can be done like that, docker and clever cloud infrastructure are you rock solid and will pull it through.

Pro
Cons
### build locally, push war to FS Bucket, COPY or ADD while building, serve it with minimum image.

My preferred approach.
Docker Image is much smaller.
Image build is nearly instantaneous.

Pro
Cons

**Comment by cnivolle** [comment]
Hi,

Your proposition seems fine. The tone of this excerpt might be adapted for a documentation tho :)
Create a pull request with your complete article, and we will validate and integrate it asap !

Cheers,
