### ISSUE TITLE
Flask Tutorial for CleverCloud

### ISSUE THREAD

**Issue by sumanau7** [CleverCloud/doc.clever-cloud.com#35]
1. How to set-up Flask App.
2. Configure Database Add-on.
3. Static File Bucket Setup.

**Comment by sumanau7** [comment]
If no one is working on it, should i take this up ?

**Comment by cnivolle** [comment]
Hi,

This article proposal seems fine, as we don't have any article about Flask.
Please send us a pull request for an article in the python section, and we will validate it.

Cheers,

**Comment by Kendos-Kenlen** [comment]
We have now an example app (#58) and a documentation available here : https://www.clever-cloud.com/doc/python/python-flask-sample-app/
