### ISSUE TITLE
Split environment variables reference and include them in runtime pages.

### ISSUE THREAD

**Issue by judu** [CleverCloud/doc.clever-cloud.com#369]
We have a page with all the environment variables used to configure the build and runtime of applications.

This page is hard to find. We should split this page in many snippets. One for each runtime. The snippets should be concatenated to make the page again. The same snippets would also be included in the documentation of each runtime.

**Comment by gaelreyrol** [comment]
I don't think this issue is still relevant, feel free to reopen.
