### ISSUE TITLE
Refresh the documentation

### ISSUE THREAD

**Issue by k33g** [CleverCloud/doc.clever-cloud.com#383]
Sometimes the information is outdated (examples are old) or it's difficult to find information (or the searched information does not exist -e.g., backup), I propose to leave this issue opened to log all things that could be improved.

**Comment by urcadox** [comment]
Let's just create an issue per subject which needs to be improved. Issues in this repo don't have any other purpose than specifying what needs to be added and what needs to be improved so a meta-issue does not make much sense.
