### ISSUE TITLE
[CLI] What is actually pushed when doing "clever deploy"

### ISSUE THREAD

**Issue by dsferruzza** [CleverCloud/doc.clever-cloud.com#404]
The [documentation](https://www.clever-cloud.com/doc/clever-tools/manage/#deploy-a-new-commit) of clever-tools says that `clever deploy` _"push your commits"_.

I believe it lacks details on what is actually pushed:

- is it the last local commit? (`HEAD`)
- what about the staging?
- what about the local changes in the working directory?
- what happens if the branch is not `master`?

**Comment by hsablonniere** [comment]
- is it the last local commit? (`HEAD`)
  - yes, we push current HEAD
- what about the staging?
  - it is ignored
- what about the local changes in the working directory?
  - it is also ignored
- what happens if the branch is not `master`?
  - we push your current branch to clever remote master

**Comment by hsablonniere** [comment]
Should we just log the commit that is being pushed?

**Comment by dsferruzza** [comment]
If you mean adding the commit ref inside clever-tools' output (⬇️), it is a good idea IMHO.

```
Pushing source code to Clever Cloud.
Your source code has been pushed to Clever Cloud
```

**Comment by hsablonniere** [comment]
See https://github.com/CleverCloud/clever-tools/issues/333

**Comment by dsferruzza** [comment]
👌 (I let you close this one, if it is relevant)
