### ISSUE TITLE
Document differences between FS Bucket and Cellar

### ISSUE THREAD

**Issue by judu** [CleverCloud/doc.clever-cloud.com#405]
We advertise them both as "storing files". Some users have a hard time differenciating the two services.

We should write a comparison article explaining:

 - What is the primary usage for both.
 - What are the upsides and downsides for both.

**Comment by dsferruzza** [comment]
In my vision when I reported this issue, the solution was something like:

- you create a new page on the doc "FS Bucket vs. Cellar"
- you explain upsides/downsides of each
- maybe discuss some classic use cases, like "I need to store avatars uploaded by my users": what is the right add-on for this? or what is the right questions to ask to be able to choose?
- reference this page from the FS Bucket page and the Cellar page

_It is only my poor point of view; the point is: I'm sure you can help people being more clever_ 😉

**Comment by dsferruzza** [comment]
@judu As you wrote https://www.clever-cloud.com/doc/addons/cellar-vs-fsbuckets/, I guess you can close this issue 🙂
