### ISSUE TITLE
Document Cloudflare + Let's Encrypt exceptions

### ISSUE THREAD

**Issue by judu** [CleverCloud/doc.clever-cloud.com#409]
For HTTPS and Cloudflare redirections, we need to document :

- [ ] How to disable Cloudflare redirect-to-https for `/.well-known/acme-challenge/*`
- [ ] How to add exception to Cloudflare's configured redirections for `/.well-known/acme-challenge/*`

**Comment by grallc** [comment]
Any news ? Kinda struggling with this   :sweat_smile:

**Comment by urcadox** [comment]
@s0dyy is working on this :)
