### ISSUE TITLE
API: HMAC-SHA512 is supported for requests signatures

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/doc.clever-cloud.com#520]
https://www.clever-cloud.com/doc/extend/cc-api/ references `PLAIN` and `HMAC-SHA1` for the signature. We also support `HMAC-SHA512`, that's what the console and probably the CLI use.

**Comment by hsablonniere** [comment]
I confirm that the CLI and console (via clever-client) use HMAC-512: https://github.com/CleverCloud/clever-client.js/blob/master/esm/oauth.browser.js#L24
