### ISSUE TITLE
Document how to change the node version on non nodejs instances

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/doc.clever-cloud.com#535]
Because we use nvm (https://github.com/nvm-sh/nvm) we can use a hook to install and use a specific version of node for the instances that do not support the node version to be set, like PHP.

Not sure where to put this though.

**Comment by gaelreyrol** [comment]
You mean this variable `CC_NODE_VERSION` ?

**Comment by BlackYoup** [comment]
Yes

**Comment by gaelreyrol** [comment]
A customer went though this, I need to work on this !

**Comment by Bencaddyro** [comment]
fixed by https://github.com/CleverCloud/doc.clever-cloud.com/pull/716
