### ISSUE TITLE
Tables: drop <center> tag and align title to the left of the column

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/doc.clever-cloud.com#583]
We currently use the `<center>` tag in all of our tables. In the reference-environment-variables page, it is hard to read the various columns because we don't really know when they start and end. Aligning the title to the left of the column could help. Maybe there could be other tricks. @hsablonniere maybe there are other things to change to make it more readable?

Should we also apply this to all of our tables?

**Comment by hsablonniere** [comment]
If I read this correctly, we only use those in the column headers, right?

**Comment by gaelreyrol** [comment]
> If I read this correctly, we only use those in the column headers, right?

I think so, we also use table in addon pricing but they are in pure html.

**Comment by hsablonniere** [comment]
TODO

* Fix shortcode (use class and style properly)
* Remove all `<center>`
* Replace `table- bordered` with `table-bordered` and make sure it's applied

**Comment by gaelreyrol** [comment]
> Fix shortcode (use class and style properly)

What do you mean ? Do you have an example ? @hsablonniere

**Comment by juliamrch** [comment]
Tables are now in pure Markdown. No more HTML.
