### ISSUE TITLE
How to deploy a Vapor application?

### ISSUE THREAD

**Issue by RemiBardon** [CleverCloud/doc.clever-cloud.com#585]
It's basically be a Dockerfile, but there might be catches or tips to add.

[The Vapor docs](https://docs.vapor.codes/4.0/deploy/docker/) gives the Dockerfile, and it's present in new projects by default, but having a guide specific for Clever Cloud could be great. The best would be to have a dedicated page on their documentation (next to DigitalOcean, Heroku and others), but I think it's better if we wait for Swift support.

**Comment by gaelreyrol** [comment]
I think this one is still to discuss on the fact that it does not rely on a dedicated runtime like with the others but Docker.

As the setup seems pretty easy and until we provide support for swift runtime, I think it would be a good thing to add below the existing [docker examples](https://www.clever-cloud.com/doc/deploy/application/docker/docker/) or simply provide a repository to play with.

What do you think @RemiBardon ?

**Comment by RemiBardon** [comment]
@gaelreyrol Yes, right, it would be better like this 👍🏻

**Comment by gaelreyrol** [comment]
Cool ! 

@BlackYoup, @ldoguin, do you agree ?

**Comment by RemiBardon** [comment]
@ldoguin [seemed to approve](https://github.com/CleverCloud/doc.clever-cloud.com/issues/259#issuecomment-824096230), I'm writing a first draft.

**Comment by gaelreyrol** [comment]
Closing in favor of: https://github.com/orgs/clever-cloud-examples/projects/1#card-64343287

**Comment by RemiBardon** [comment]
Why did you close it? Couldn't we just rename it and use it as a card in the new board?
