### ISSUE TITLE
Update pricing tables for database add-ons

### ISSUE THREAD

**Issue by gaelreyrol** [CleverCloud/doc.clever-cloud.com#595]
The idea is to use [cc-pricing-product](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-product--default-story) as a smart component to display up to date pricing and information.

We should integration this component on database add-on page.

We want to:
- [x] Moved pricing plans at the bottom
- [x] Use partial template using variables
- [x] Change `max-width` et remove `no-gutter` & `padding: 5vw` in [hugo-cc-doc-theme](https://github.com/CleverCloud/hugo-cc-doc-theme)

There are some requirements before doing so such as style adjustments.

**Comment by hsablonniere** [comment]
* I started this issue https://github.com/CleverCloud/clever-components/issues/258 so the component can be simplified for view only.
* We will need to adjust the size of the main bloc of content and the position of the right nav.

**Comment by gaelreyrol** [comment]
We want to use the `cc-pricing-table` as a smart component, cf https://github.com/CleverCloud/clever-components/issues/259

**Comment by gaelreyrol** [comment]
But @hsablonniere found a way to bypass the head definition of `cc-pricing-product` to prevent icon, title and description from appearing !
