### ISSUE TITLE
Document timezones in a more global page

### ISSUE THREAD

**Issue by PierreZ** [CleverCloud/doc.clever-cloud.com#601]
Currently, we can find documentation about [timezones in the PHP page](https://github.com/CleverCloud/doc.clever-cloud.com/blob/master/partials/language-specific-deploy/php.md#timezone-configuration):

> All instances on Clever Cloud run on the UTC timezone. We recommend to handle all your dates in UTC internally, and only handle timezones when reading or displaying dates.

Or in the [cron page](https://www.clever-cloud.com/doc/administrate/cron/#syntax) as a warning:

> All the servers are configured to use Coordinated Universal Time (UTC), please keep it in mind when configuring cron tasks to run at a specific hour.

Should we expose this information in a more global page? I was thinking maybe:

* a dedicated page in the `Administrate` section
* an item in the FAQ

**Comment by gaelreyrol** [comment]
I think an item in the FAQ would be fine! Do you want create the PR?
