### ISSUE TITLE
Document how to use Cloudflare with Clever Cloud

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/doc.clever-cloud.com#610]
We should document how to use Cloudflare with Clever Cloud. Specifically how to have working Let's Encrypt certificates.

Here's how:

1. Define a page rule such as this one:
![2021-05-31_15-54-33](https://user-images.githubusercontent.com/891612/120204357-00ee5880-c229-11eb-891e-d281739a684a.png)

2. Disable HTTP to HTTPS redirection on Cloudflare (enable "Force HTTPS" in the information tab of your Clever Cloud application instead):
![2021-05-31_15-55-13](https://user-images.githubusercontent.com/891612/120204409-0ea3de00-c229-11eb-80e6-568313e214f0.png)

**Comment by gaelreyrol** [comment]
@urcadox Is the second point useful ? As the page rule already include https bypass.

**Comment by urcadox** [comment]
The page rule does not actually bypass https. I'm pretty sure disabling "automatic https rewrites" does not help, I just put it there just in case.

**Comment by gaelreyrol** [comment]
Indeed, the [documentation](https://support.cloudflare.com/hc/en-us/articles/227227647) states that this rule only affect automatic HTTPS redirects IF available.
