### ISSUE TITLE
Split runtime main doc and configuration doc

### ISSUE THREAD

**Issue by Kendos-Kenlen** [CleverCloud/doc.clever-cloud.com#67]
To avoid too long file, and to have something more clear, it could be a good idea to split the main documentation of a runtime (ex PHP) and the part about configuration.

What do you think about?

**Comment by urcadox** [comment]
Ouch that's quite an old issue. I guess this could make sense bu right now, for most runtimes, the whole doc is about configuration so I'm not sure what we could split.

Closing this for now, we have bigger issues to solve.
