### ISSUE TITLE
Nodejs its so old

### ISSUE THREAD

**Issue by Geruays** [CleverCloud/doc.clever-cloud.com#719]
How do i upgrade to 16?

**Comment by gaelreyrol** [comment]
Hi @Geruays, have you define your Node.js version in your `package.json` ?

**Comment by Geruays** [comment]
> Hi @Geruays, have you define your Node.js version in your `package.json` ?

can you tell me how to do that?

**Comment by gaelreyrol** [comment]
@Geruays You can define the object `engines.node` like so:
```json
{
  "engines": {
    "node": ">=0.10.3 <15"
  }
}
```
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines
