### ISSUE TITLE
Explain how to automatically restart a nodejs app

### ISSUE THREAD

**Issue by abenhamdine** [CleverCloud/doc.clever-cloud.com#74]
I can't find any explanation in the doc about how to set automatic restart for a nodejs app.

I only find one mention in google about "clevercloud automatically restart the app"
http://blog.clement.delafargue.name/posts/2014-03-13-snap-framework-apps-over-clevercloud.html

Is it actually the case ?
And if it is the case, what is the delay for detecting a crash and trigger the restart ?

**Comment by BlackYoup** [comment]
Hi,

Sorry, we missed that one. Yes, if the app crashes, we start a new deployment right away to bring the application back. There is no delay (except the deployment process) in case of a direct crash / process exited

**Comment by abenhamdine** [comment]
thx for the answer !
I would be glad to submit a PR, if you are open on this.

**Comment by BlackYoup** [comment]
Yes, we are. Contributions are open and welcome. Feel free to submit a PR and we will review it :)

Thanks !

**Comment by divarvel** [comment]
I think the best place would be in https://www.clever-cloud.com/doc/clever-cloud-overview/intro-to-apps/ which needs an overhaul anyway.

**Comment by urcadox** [comment]
Everything has been said here, a PR would be welcomed.
