### ISSUE TITLE
Update FS Buckets documentation, with examples

### ISSUE THREAD

**Issue by rbatty19** [CleverCloud/doc.clever-cloud.com#864]
I found myself dry trying to implementate FS Buckets with a PHP proyect

There's no example or something similar.

- How to upload from the application
- How to download
- How to check the filetree (nice to have)

so far, I'm using FTP to interact with the bucket

**Comment by alexislefebvre** [comment]
You can find examples here: https://www.clever-cloud.com/blog/features/2017/09/22/fs-bucket-environment-variable/

Example:

```env
CC_FS_BUCKET=/my_uploads:bucket_host
```
